# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Test
on:
  workflow_call:     # Allow other workflows to use it
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

    # Install the .NET SDK indicated in the global.json file
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4

    # Restore nuget packages only once
    - name: Restore
      run: dotnet restore

    # Build binaries
    - name: Build with dotnet
      run: dotnet build --no-restore --configuration Release

    # Run tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal --configuration Release
